const EXPECTED_BACKEND_COLUMNS = {
  etiquetas: ["id_etiqueta", "etiqueta", "categoria_pnl"],
  acreedores: ["id_acreedor", "origen_tipo_acreedor", "origen_id_acreedor", "cuit_cuil", "cbu_alias", "acuerdo_de_pago"],
  otros_acreedores: ["id_otro_acreedor", "nombre_otro_acreedor"],
  acreedores_etiquetas: ["id_acreedor_etiqueta", "id_acreedor", "id_etiqueta"],
  proveedores: ["id_proveedor", "nombre", "telefono", "email", "tiempo_estimado_entrega", "pedido_minimo"],
  clientes: ["id_cliente", "nombre_cliente", "cuit", "direccion", "localidad", "contacto", "telefono", "email", "id_canal", "tipo", "tipo_comprobante", "plazo_cobro"],
  empleados: ["id_empleado", "nombre_empleado", "categoria_empleado", "fecha_alta", "fecha_baja", "dni", "fecha_nacimiento", "direccion_empleado", "localidad_empleado"],
  canales: ["id_canal", "nombre", "comision"],
  fletes: ["id_flete", "nombre_flete", "telefono_flete", "email_flete"],
  datos_bancarios: ["id_dato_bancario", "detalle", "id_acreedor", "id_etiqueta", "tipo_factura"],
  movimientos_bancarios: ["id_movimiento_bancario", "banco", "fecha", "cod_concepto", "concepto", "detalle", "cuit", "nro_cheque", "debito", "credito", "importe", "saldo", "id_pago", "id_cobro", "id_movimiento_fondo"],
  fondos_inversion_movimientos: ["id_movimiento_fondo", "fecha", "tipo", "importe", "periodo_rendimiento", "id_movimiento_bancario", "id_pago", "id_gasto_economico", "referencia", "observacion", "clave_idempotencia", "hash_payload", "creado_en"],
  items: ["id_item", "origen_tipo", "id_origen", "ud_conteo"],
  productos: ["id_producto", "id_item", "nombre_producto", "capacidad_palet", "cantidad_individual", "precio_base", "costo_base", "costo_ud_individual"],
  subproductos: ["id_subproducto", "id_item", "nombre_subproducto", "ud_conteo"],
  insumos: ["id_insumo", "nombre", "ud_receta", "cantidad_receta", "tipo"],
  insumos_proveedores: ["id_insumos_proveedores", "id_insumo", "id_proveedor", "ud_proveedor", "cantidad_proveedor", "precio", "iva"],
  recetas: ["id_receta", "id_item_resultado", "id_item_componente", "cantidad_componente", "unidad_base"],
  pedidos: ["id_pedido", "fecha_pedido", "id_cliente", "fecha_entrega", "fecha_original"],
  detalle_pedidos: ["id_detalle_pedido", "id_pedido", "id_producto", "cantidad_cajas", "impuesto", "precio_ud", "bonificacion"],
  entregas: ["id_entrega", "fecha", "id_flete", "id_acreedor_etiqueta", "id_egreso"],
  entregas_detalle: ["id_entregas_detalle", "id_entrega", "id_pedido"],
  ventas: ["id_venta", "id_pedido", "id_cliente", "id_entrega", "tipo_factura", "nro_factura", "fecha_factura", "fecha_acordada", "iva", "subtotal", "total"],
  gestion_ventas: ["id_gestion_venta", "id_pedido", "origen", "clave_creacion_pedido", "hash_creacion_pedido", "factura_arca_confirmada_en", "factura_arca_confirmada_por", "archivo_factura", "archivo_factura_nombre", "archivo_factura_hash", "cerrado_en", "cerrado_por", "creado_en", "actualizado_en"],
  cobros: ["id_cobro", "fecha_cobro", "metodo", "id_cliente", "monto", "banco"],
  cobros_detalle: ["id_cobros_detalle", "id_cobro", "id_venta", "monto_cancelado"],
  retenciones_ganancias: ["id_retencion_ganancias", "id_cobro", "fecha", "id_cliente", "monto"],
  retenciones_iibb: ["id_retencion_iibb", "id_cobro", "fecha", "id_cliente", "monto"],
  caja: ["cuenta", "monto"],
  cheques_entregados: ["id_cheque_entregado", "id_pago", "id_acreedor", "nro_cheque", "fecha_entregado", "fecha_uso", "monto", "banco", "estado"],
  cheques_recibidos: ["id_cheque_recibido", "id_cobro", "fecha_entregado", "monto", "cliente", "id_cliente", "nro_cheque", "fecha_uso", "estado", "banco", "fecha_deposito", "id_deposito", "id_pago_endoso", "fecha_endoso"],
  compras: ["id_compra", "id_proveedor", "fecha_pedido", "fecha_entrega_prevista"],
  detalle_compras: [
    "id_detalle_compra",
    "id_compra",
    "id_insumos_proveedores",
    "cantidad"
  ],
  recepciones: ["id_recepcion", "fecha_recepcion", "id_empleado", "id_compra", "id_acreedor_etiqueta", "id_egreso", "archivo_recepcion"],
  detalle_recepciones: ["id_detalle_recepcion", "id_recepcion", "id_insumo", "cantidad_recibida"],
  otros_gastos: ["id_otros_gastos", "fecha_otros_gastos", "id_acreedor", "id_acreedor_etiqueta", "id_egreso", "detalle"],
  aportes_socios: ["id_aporte_socio", "fecha", "nombre", "tipo", "monto", "id_egreso"],
  planes_pagos: ["id_plan_pago", "nombre", "organismo"],
  cuotas_planes_pagos: ["id_cuota_plan_pago", "id_plan_pago", "nro_cuota", "capital", "interes_financiero", "interes_resarcitorio", "total_primer_vencimiento", "fecha_primer_vencimiento", "total_segundo_vencimiento", "fecha_segundo_vencimiento", "id_egreso"],
  egresos: ["id_egreso", "fecha_factura", "fecha_prevista_pago", "id_etiqueta", "tipo_factura", "nro_factura", "iva", "per_ret_iva", "per_ret_iibb", "imp_internos", "subtotal", "total"],
  pagos: ["id_pago", "fecha_pago", "metodo", "banco", "monto"],
  detalle_pagos: ["id_detalle_pago", "id_pago", "id_egreso", "monto_cancelado"],
  sueldos: ["id_sueldo", "fecha", "id_empleado", "id_acreedor_etiqueta", "id_egreso", "valor_remunerativo", "valor_no_remunerativo", "hs_trabajadas", "hs_con_justificacion_medica", "hs_feriado", "hs_extra", "premios", "sueldo_bruto", "sueldo_neto"],
  comisiones: ["id_comision", "fecha", "id_canal", "id_acreedor_etiqueta", "id_egreso", "id_venta", "subtotal", "comision"],
  sueldos_calculo: ["id_sueldo", "fecha", "id_empleado", "valor_remunerativo", "valor_no_remunerativo", "hs_trabajadas", "hs_con_justificacion_medica", "hs_feriado", "hs_extra", "premios", "sueldo_bruto", "sueldo_neto"],
  gastos_economicos: ["id_gasto_economico", "fecha_economica", "id_etiqueta", "concepto", "tipo_economico", "tipo_movimiento", "importe", "estado", "origen_tipo", "origen_id", "origen_subclave", "id_gasto_precedente", "motivo", "clave_idempotencia", "hash_payload", "creado_en", "actualizado_en", "confirmado_en"],
  gastos_egresos: ["id_gasto_egreso", "id_gasto_economico", "id_egreso", "importe_aplicado", "componente_egreso", "componente_otro", "tipo_aplicacion", "estado", "id_aplicacion_precedente", "motivo", "clave_idempotencia", "hash_payload", "creado_en"],
  inventarios: ["id_inventario", "fecha", "turno", "id_empleado", "valor_total"],
  detalle_inventarios: ["id_detalle_inventario", "id_inventario", "id_item", "cantidad", "costo_unitario_usado", "valor_total"]
};

module.exports = { EXPECTED_BACKEND_COLUMNS };
